

graph LR
    Build[**Plan** and **Build** in **Cursor**]
        --> Push["**Push** to **Github** Repository"]
        --> Host["**Host** on **Vercel.com**"]
	Database[**Setup Backend Database** on **InstantDB.com**]
	Database-->Host
